services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000"]
      interval: 300s
      retries: 3
      start_period: 10s
      timeout: 10s