[tool.pytest.ini_options]
pythonpath = "."
addopts = "--cov=app --cov-report=term-missing --cov-report=html --cov-config=coverage.ini"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]

[tool.isort]
profile = "black"
