[tool.pytest.ini_options]
pythonpath = "."
addopts = "--cov=app --cov-report=term-missing --cov-report=html --cov-config=coverage.ini"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]

[tool.isort]
profile = "black"

[tool.black]
line-length = 160

[tool.pylint."MESSAGES CONTROL"]
max-line-length = 160

[tool.mypy]
strict = true
ignore_missing_imports = true